# .github/workflows/deploy.yaml

name: Deploy to Google App Engine
on:
  push:
    branches:
      - master
jobs:
  build:
    name: GAE Deploy
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - name: Install Node.js dependencies
      run: npm install

    # Runs lint
    - name: Run lint
      run: npm run lint

    # Runs test
    - name: Run test
      run: npm test
